# -*- coding: utf-8 -*-
"""Copy of API TO DataFrame.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1OFTYAfHlb71RnwDJ8B0ViT81oeJPVBTw
"""

import pandas as pd 
import numpy as np

import requests


r = requests.get('https://9gnht4xyvf.execute-api.eu-west-1.amazonaws.com/api/get_table/CounterMeasureView')
r
# x = r.json()
# df = pd.DataFrame(x)
# df.head(20).to_html()

import pandas as pd 
import requests
url = "https://9gnht4xyvf.execute-api.eu-west-1.amazonaws.com/api/get_table/CasesGlobalView"
headers = {
    'x-api-key': "WVllUkRA01awNNgKxGg607vl5qIvuOAN3pW9HXmD"
    }
response = requests.request("GET", url, headers=headers)
x = response.json()
df = pd.DataFrame(x)
df
# df.head(20).to_html()

