# -*- coding: utf-8 -*-
"""Pred_Powerball.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1y2AV451zdAd8h-6hvNktDK4EBd0tWjmI

mean = sum of x vals /n

xbar =(x1+x2+x2+...+xn)/n

median =(x1+x2+x3+..+xn+x_predict)/n+1

https://www.lottology.com/south-africa/powerball/?do=past-draws-archive&table_view_type=draws&year=2021&numbers=10.26.27.28.29.30.31.32.33.34.35.36.37.38.39.40.41.42.43.44.45.46.47.48.49.50#google_vignette
"""

import pandas as pd
import numpy as np

pd.read_excel("/powerball-past-draws-archive (2).xls")

df= pd.read_excel("/powerball-past-draws-archive (2).xls",header=4)

df

df1=df.loc[df['Day Of Week']=='Friday']
df2=df.loc[df['Day Of Week']=='Tuesday']

df1

df.info()

df.describe()

df1

df2['PowerBall'].median()-105*df2['PowerBall'].mean()

import random

np.random.uniform(low=1, high=20, size=1)

np.random.uniform(low=1, high=50, size=5)

np.random.randit(51 ,size=6)

print(2570%50,2575%50,2505%50,2712%50,2109%50,1074%20)

print(3292%50,3048%50,2463%50,2694%50,2432%50)

2935%50

df['2'].median()-105*df['2'].mean()

2814%50

df['3'].median()-105*df['3'].mean()

2484%50

df['4'].median()-105*df['4'].mean()

2703%50

df['5'].median()-105*df['5'].mean()

2274%50

df['PowerBall'].median()-105*df['PowerBall'].mean()

1086%20

-1%50

-145%20

19%20

(1+50)/2

(51/2)*(50/49)

